{% set name = "plotly" %}
{% set version = "3.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8e1b323b20bb2e726cd1d5ea73c6ca7b13664513f7846e283cfed775f7cc4b26

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
    - nodejs
  run:
    - decorator >=4.0.6
    - nbformat >=4.2
    - python
    - pytz
    - requests
    - retrying >=1.3.3
    - six

test:
  imports:
    - plotly

about:
  home: https://plot.ly/python/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An open-source, interactive graphing library for Python
  dev_url: https://github.com/plotly/plotly.py

extra:
  recipe-maintainers:
    - xhochy
